use gpui::SharedString;
use gpui_component::IconNamed;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(dead_code)]
pub enum Icon {
    Bird,
    Play,
    Pause,
    Square,
    Settings,
    FolderOpen,
    Save,
    Download,
    Undo,
    Redo,
    Bug,
    Eraser,
    Search,
    Smartphone,
    Monitor,
    Braces,
    Camera,
    Charts,
    Sliders,
    Accessibility,
    Gauge,
    ShoppingBag,
    ShieldCheck,
    Map,
    Columns,
    Layers,
    ArrowUpDown,
    Check,
    TriangleAlert,
    X,
    PanelRightOpen,
    Moon,
    LayoutPanelLeft,
    CircleHelp,
    LoaderCircle,
    CircleDot,
    Globe,
    Link,
    Image,
    Code,
    FileCode,
    FileSearch,
    List,
    Ban,
    Filter,
    Lock,
    Unlock,
    ExternalLink,
    CircleAlert,
    Info,
    CircleX,
    CircleCheck,
    Tag,
    Tags,
    Percent,
    Stop,
    RefreshCw,
}

impl Icon {
    fn slug(self) -> &'static str {
        use Icon::*;
        match self {
            Bird => "bird",
            Play => "play",
            Pause => "pause",
            Square => "square",
            Settings => "settings",
            FolderOpen => "folder-open",
            Save => "save",
            Download => "download",
            Undo => "undo-2",
            Redo => "redo-2",
            Bug => "bug",
            Eraser => "eraser",
            Search => "search",
            Smartphone => "smartphone",
            Monitor => "monitor",
            Braces => "braces",
            Camera => "camera",
            Charts => "chart-no-axes-combined",
            Sliders => "sliders-horizontal",
            Accessibility => "accessibility",
            Gauge => "gauge",
            ShoppingBag => "shopping-bag",
            ShieldCheck => "shield-check",
            Map => "map",
            Columns => "columns-3",
            Layers => "layers",
            ArrowUpDown => "arrow-up-down",
            Check => "check",
            TriangleAlert => "triangle-alert",
            X => "x",
            PanelRightOpen => "panel-right-open",
            Moon => "moon",
            LayoutPanelLeft => "layout-panel-left",
            CircleHelp => "circle-help",
            LoaderCircle => "loader-circle",
            CircleDot => "circle-dot",
            Globe => "globe",
            Link => "link-2",
            Image => "image",
            Code => "code",
            FileCode => "file-code",
            FileSearch => "file-search",
            List => "list",
            Ban => "ban",
            Filter => "filter",
            Lock => "lock",
            Unlock => "unlock",
            ExternalLink => "external-link",
            CircleAlert => "circle-alert",
            Info => "info",
            CircleX => "circle-x",
            CircleCheck => "circle-check",
            Tag => "tag",
            Tags => "tags",
            Percent => "percent",
            Stop => "square-stop",
            RefreshCw => "refresh-cw",
        }
    }
}

impl IconNamed for Icon {
    fn path(self) -> SharedString {
        SharedString::from(format!("icons/{}.svg", self.slug()))
    }
}
