[package]
name = "shoutingrobin-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/ui.rs"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
ropey = "=2.0.0-beta.1"
serde_json = { workspace = true }
smallvec = "1"
