ALTER TABLE pages ADD COLUMN sd_errors INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pages ADD COLUMN sd_warnings INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pages ADD COLUMN hreflang_tags_json TEXT;
ALTER TABLE pages ADD COLUMN sd_types_json TEXT
