ALTER TABLE pages ADD COLUMN og_type TEXT;

ALTER TABLE ecommerce ADD COLUMN brand TEXT;
ALTER TABLE ecommerce ADD COLUMN has_image BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE ecommerce ADD COLUMN has_description BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE ecommerce ADD COLUMN has_review_or_rating BOOLEAN NOT NULL DEFAULT 0
